version: '2.4'

services:
  frontend:
    image: ${WEBAPP_IMAGE}
    ports:
      - "80:5000"
    env_file:
        - .env
    restart: always
  backend:
    image: ${API_IMAGE}
    ports:
      - "4000:5000"
    env_file:
      - .env
    restart: always
